### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by HansieNL** [t1m0thyj/AssistantPi#1]
I tried the clone option on Raspberry Pi 3b, Raspbian Stretch June 2018.
I get some error messages:
**pyasn1-modules 0.2.2 has requirement pyasn1<0.5.0,>=0.4.1, but you'll have pyasn1 0.1.9 which is incompatible.
google-api-core 0.1.4 has requirement requests<3.0.0dev,>=2.18.0, but you'll have requests 2.14.2 which is incompatible.**
and later the following error messages:
**Traceback (most recent call last):
  File "src/AssistantPi.py", line 29, in <module>
    import aiy.assistant.auth_helpers
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 25, in <module>
    import google_auth_oauthlib.flow
ImportError: No module named 'google_auth_oauthlib'**
Can you tell me what's going wrong?

**Comment by t1m0thyj** [comment]
I believe the first two error messages about incompatible packages shouldn't matter. I know my Pi had the same message for at least the `requests` module.

Regarding the second error, thanks for reporting this. It probably means that you're the first person to use my scripts on a Pi that has not an older version of the Assistant SDK installed previously. That's why I didn't notice this on my own Pi, I think there are some Google libraries it still has installed somewhere.

Could you try navigating to the `~/AIY-projects-python` folder in a terminal window and run the following command:
`env/bin/pip install google-auth-oauthlib`

Then to test if Assistant is working, run this comand:
`source env/bin/activate && env/bin/python3 -u src/AssistantPi.py`

I think the cause of this problem may be that Google forgot to include the `google-auth-oauthlib` package in their list of dependencies. If so, I can submit a PR to their repo to get it fixed.

**Comment by HansieNL** [comment]
I executed the above commands. I had to give permission and confirm my account. That's working :-)
When I execute source env/bin/activate && env/bin/python3 -u src/AssistantPi.py I get the following error warning:
**ON_MUTED_CHANGED:
  {'is_muted': False}[1169:1191:ERROR:audio_input_processor.cc(748)] Input error

/home/pi/AIY-projects-python/src/aiy/_drivers/_led.py:51: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(channel, GPIO.OUT)
ON_START_FINISHED
Say "OK, Google" then speak, or press Ctrl+C to quit...
[1169:1199:ERROR:audio_input_processor.cc(748)] Input error**

Should the assistant already be working right now? Please advice.

FYI: I'm using a Voice Kit from MagPi 57.

**Comment by t1m0thyj** [comment]
I hadn't realized you were using the Voice Kit, that makes a difference. I haven't worked with one, but I think you need to install some drivers on your Pi to make them work. I should add a note mentioning this in the README, since that's an additional step required compared to if you had your own USB speakers and mic already configured with the Pi.

I would suggest following the instructions [here](https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/HACKING.md#voice-bonnet-minimal-setup) for "Voice Bonnet Minimal Setup", since I think that's what Google has you do to setup the audio. If that doesn't work I'm afraid I'm going to have more difficulty helping, since as I said I don't have a Voice Kit, but please report back how it goes.

**Comment by HansieNL** [comment]
Tried the Voice Bonnet Minimal Setup, but still keeps an GPIO error. I don't know how to fix that.
The AIY Kits Release image works out of the box, so I'll stick with that release.
Thanks for your help anyway.

**Comment by t1m0thyj** [comment]
I decided to get an AIY Voice Kit myself, so I had to figure out how to set it up. I've added an `install-hat.sh` script that should hopefully work to install the driver for the HAT.
