### ISSUE TITLE
Installation failed at the end

### ISSUE THREAD

**Issue by rihardiii** [t1m0thyj/AssistantPi#5]
Hi, i have Raspbian Lite stretch (i think, the newest one, fresh install) and i am getting this error constantly:
google-api-core 0.1.4 has requirement requests<3.0.0dev,>=2.18.0, but you'll have requests 2.14.2 which is incompatible.

and:

Created symlink /etc/systemd/system/multi-user.target.wants/AssistantPi.service -> /lib/systemd/system/AssistantPi.service.
Traceback (most recent call last):
  File "src/AssistantPi.py", line 31, in <module>
    import aiy.audio
  File "/home/pi/AIY-projects-python/src/aiy/audio.py", line 17, in <module>
    import numpy as np
ImportError: No module named 'numpy'

**Comment by t1m0thyj** [comment]
I believe the problem is that Raspbian Lite is missing some dependencies that are already present in the full version of Raspbian. Try opening a terminal in the directory `/home/pi/AIY-projects/python` and run these commands:
```
bash uninstall.sh
sudo apt-get install python3-dev python3-numpy
bash install.sh
```
This should clean up the broken install, install the Python 3 `dev` and `numpy` packages, and then hopefully install successfully.

Let me know if you encounter any other issues. If this works, I'll add installing these dependencies to the `install.sh` script so the problem won't happen again.

**Comment by rihardiii** [comment]
installing numpy helped, dev tools already installed before because saw thet in previous thread.
Thank you!
